In [ ]:
import pandas as pd
import numpy as np

# Q1: From the winequality.csv extract the first 100 rows and the 12 columns
url = "https://raw.githubusercontent.com/benny472/BehnamSafayi/main/winequality.csv"
W = pd.read_csv(url,header=0, sep=";")
W1 = W.iloc[:100,:12]
W1

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
95,4.7,0.600,0.17,2.3,0.058,17.0,106.0,0.9932,3.85,0.60,12.9,6
96,6.8,0.775,0.00,3.0,0.102,8.0,23.0,0.9965,3.45,0.56,10.7,5
97,7.0,0.500,0.25,2.0,0.070,3.0,22.0,0.9963,3.25,0.63,9.2,5
98,7.6,0.900,0.06,2.5,0.079,5.0,10.0,0.9967,3.39,0.56,9.8,5
99,8.1,0.545,0.18,1.9,0.080,13.0,35.0,0.9972,3.30,0.59,9.0,6

In [ ]:
# Q2: Transform in the numpy array A
A = np.array(W1)

# Q3: Calculate the dot product Y = A'A
AT = A.transpose()
Y = np.dot(AT,A)

# Q4: Print the result Y
print("Y = A'A = ", "\n", Y)

Y = A'A =
 [[5.85812000e+03 4.19407000e+02 1.74197000e+02 1.86772000e+03
  7.69230000e+01 1.23206000e+04 4.34820000e+04 7.55627690e+02
  2.51578500e+03 5.46827000e+02 7.39277000e+03 3.98680000e+03]
 [4.19407000e+02 3.40927500e+01 1.03470500e+01 1.38687500e+02
  5.60568000e+00 8.85785000e+02 3.10063000e+03 5.58650705e+01
  1.87490450e+02 3.87845500e+01 5.49421500e+02 2.91255000e+02]
 [1.74197000e+02 1.03470500e+01 7.88790000e+00 5.26160000e+01
  2.49596000e+00 3.80100000e+02 1.43844000e+03 2.17055190e+01
  7.16164000e+01 1.70796000e+01 2.12316000e+02 1.13980000e+02]
 [1.86772000e+03 1.38687500e+02 5.26160000e+01 7.87795000e+02
  2.40570000e+01 4.25180000e+03 1.47710000e+04 2.45070420e+02
  8.20027000e+02 1.70986000e+02 2.41782000e+03 1.29030000e+03]
 [7.69230000e+01 5.60568000e+00 2.49596000e+00 2.40570000e+01
  1.48158400e+00 1.69619000e+02 5.86514000e+02 1.00243492e+01
  3.30954200e+01 7.96366000e+00 9.77174000e+01 5.27770000e+01]
 [1.23206000e+04 8.85785000e+02 3.80100000e+02 4.25180000e+03
  1.69619000e+02 3.65130000e+04 1.19054000e+05 1.59012370e+03
  5.28421000e+03 1.18413000e+03 1.55340000e+04 8.37700000e+03]
 [4.34820000e+04 3.10063000e+03 1.43844000e+03 1.47710000e+04
  5.86514000e+02 1.19054000e+05 4.56215000e+05 5.62146580e+03
  1.85972600e+04 4.45281000e+03 5.51996000e+04 2.93000000e+04]
 [7.55627690e+02 5.58650705e+01 2.17055190e+01 2.45070420e+02
  1.00243492e+01 1.59012370e+03 5.62146580e+03 9.93543653e+01
  3.32255499e+02 7.05888310e+01 9.75107980e+02 5.23302500e+02]
 [2.51578500e+03 1.87490450e+02 7.16164000e+01 8.20027000e+02
  3.30954200e+01 5.28421000e+03 1.85972600e+04 3.32255499e+02
  1.11375120e+03 2.33042700e+02 3.26649900e+03 1.74910000e+03]
 [5.46827000e+02 3.87845500e+01 1.70796000e+01 1.70986000e+02
  7.96366000e+00 1.18413000e+03 4.45281000e+03 7.05888310e+01
  2.33042700e+02 5.92503000e+01 6.91622000e+02 3.73050000e+02]
 [7.39277000e+03 5.49421500e+02 2.12316000e+02 2.41782000e+03
  9.77174000e+01 1.55340000e+04 5.51996000e+04 9.75107980e+02
  3.26649900e+03 6.91622000e+02 9.61733000e+03 5.13980000e+03]
 [3.98680000e+03 2.91255000e+02 1.13980000e+02 1.29030000e+03
  5.27770000e+01 8.37700000e+03 2.93000000e+04 5.23302500e+02
  1.74910000e+03 3.73050000e+02 5.13980000e+03 2.79900000e+03]]

In [ ]:
# Q5: Reshape A as an array with dimension (?,25,12)
RA = np.reshape(A,(-1,25,12))
print(RA.shape, "\n")
print(RA)

(4, 25, 12)

[[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
  [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
  [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
  ...
  [ 7.9    0.43   0.21  ...  0.91   9.5    5.   ]
  [ 8.5    0.49   0.11  ...  0.53   9.4    5.   ]
  [ 6.9    0.4    0.14  ...  0.63   9.7    6.   ]]

 [[ 6.3    0.39   0.16  ...  0.56   9.3    5.   ]
  [ 7.6    0.41   0.24  ...  0.59   9.5    5.   ]
  [ 7.9    0.43   0.21  ...  0.91   9.5    5.   ]
  ...
  [ 8.7    0.29   0.52  ...  0.58   9.5    5.   ]
  [ 6.4    0.4    0.23  ...  0.56   9.2    5.   ]
  [ 5.6    0.31   0.37  ...  0.58   9.2    5.   ]]

 [[ 8.8    0.66   0.26  ...  0.74   9.2    5.   ]
  [ 6.6    0.52   0.04  ...  0.63   9.4    6.   ]
  [ 6.6    0.5    0.04  ...  0.64   9.4    6.   ]
  ...
  [ 7.7    0.69   0.22  ...  0.48   9.5    5.   ]
  [ 8.3    0.675  0.26  ...  0.53   9.2    4.   ]
  [ 9.7    0.32   0.54  ...  0.82   9.6    5.   ]]

 [[ 8.8    0.41   0.64  ...  0.66  10.5    5.   ]
  [ 8.8    0.41   0.64  ...  0.66  10.5    5.   ]
  [ 6.8    0.785  0.    ...  0.55  10.7    6.   ]
  ...
  [ 7.     0.5    0.25  ...  0.63   9.2    5.   ]
  [ 7.6    0.9    0.06  ...  0.56   9.8    5.   ]
  [ 8.1    0.545  0.18  ...  0.59   9.     6.   ]]]

In [ ]:
# Q6: Create a function able to make the dot product of two matrices and return the sum of all elements of the result
def funw(x,y):

    return np.sum(np.dot(x,y))

# example
S = funw(AT,A)
print("Sum of all elements = ", S)

Sum of all elements =  1280327.29755672